### PR TITLE
Separate languages settings for anthropic + add Hebrew (with Niqqud) as language

### PR DESCRIPTION
**Pull request by seidnerj**
It's all in the title.

### CODE REVIEW

**Comment by bookfere** [comment]
Thank you for your PR.

Using type hints is certainly a good practice, but we need to ensure compatibility with older versions of Calibre (which embed Python 2.x).

We could also focus on supporting newer versions of Calibre only, though this would make it unavailable to users who cannot upgrade to the newer version of Calibre. I'd love to hear your thoughts on this.

**Comment by seidnerj** [comment]
My pleasure!

Well, Python 2.x usage has virtually ceased, according to the latest stats it is less than 5% of the Python usage today, maybe less. My 2 cents are is that we'll have to cut the cord at some point, now seems as good a time as any. Don't think it'll have major repercussions for Cablire/this plugin's user base.

**Comment by bookfere** [comment]
It makes sense. I hesitated for a while, struggling with not being able to use Python's newer features while maintaining two versions of the code. Maybe it's time to move forward.

Since Calibre supports Python 3 starting from version 5, how about we set the minimum supported version for the plugin to version 5 and use Python 3.8.5 (which is embedded in Calibre 5) as our baseline?

**Comment by seidnerj** [comment]
Makes complete sense to me 🙂

**Comment by bookfere** [comment]
Alright, the last release will be the final one to support Calibre versions that use Python 2. We can go ahead and clean up the codebase to remove any Python 2-compatible code.

**Comment by seidnerj** [comment]
Great! This will make development both easier and faster.

**Pull request merged**
